FROM openjdk:21

# Nhận biến
ARG POSTGRES_USERNAME
ARG POSTGRES_PASSWORD
ARG POSTGRES_URL
ARG JWT_SECRET
ARG OAUTH2_GOOGLE_CLIENT_ID
ARG OAUTH2_GOOGLE_CLIENT_SECRET
ARG ACCOUNT_CLOUDFLARE_API_TOKEN
ARG ACCOUNT_CLOUDFLARE_API_ACCOUNT_ID
ARG ACCOUNT_AZURE_KEY
ARG CLOUD_CLOUDINARY_NAME
ARG CLOUD_CLOUDINARY_API_KEY
ARG CLOUD_CLOUDINARY_API_SECRET

# Đặt vào để đọc
ENV POSTGRES_USERNAME=$POSTGRES_USERNAME \
    POSTGRES_PASSWORD=$POSTGRES_PASSWORD \
    POSTGRES_URL=$POSTGRES_URL \
    JWT_SECRET=$JWT_SECRET \
    OAUTH2_GOOGLE_CLIENT_ID=$OAUTH2_GOOGLE_CLIENT_ID \
    OAUTH2_GOOGLE_CLIENT_SECRET=$OAUTH2_GOOGLE_CLIENT_SECRET \
    ACCOUNT_CLOUDFLARE_API_TOKEN=$ACCOUNT_CLOUDFLARE_API_TOKEN \
    ACCOUNT_CLOUDFLARE_API_ACCOUNT_ID=$ACCOUNT_CLOUDFLARE_API_ACCOUNT_ID \
    ACCOUNT_AZURE_KEY=$ACCOUNT_AZURE_KEY \
    CLOUD_CLOUDINARY_NAME=$CLOUD_CLOUDINARY_NAME \
    CLOUD_CLOUDINARY_API_KEY=$CLOUD_CLOUDINARY_API_KEY \
    CLOUD_CLOUDINARY_API_SECRET=$CLOUD_CLOUDINARY_API_SECRET

COPY target/aishortvideo-0.0.1-SNAPSHOT.jar app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]

EXPOSE 9090