FROM openjdk:21

ARG POSTGRES_USERNAME
ENV POSTGRES_USERNAME=${POSTGRES_USERNAME}

ARG POSTGRES_PASSWORD
ENV POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

ARG POSTGRES_URL
ENV POSTGRES_URL=${POSTGRES_URL}

ARG JWT_SECRET
ENV JWT_SECRET=${JWT_SECRET}

ARG OAUTH2_GOOGLE_CLIENT_ID
ENV OAUTH2_GOOGLE_CLIENT_ID=${OAUTH2_GOOGLE_CLIENT_ID}

ARG OAUTH2_GOOGLE_CLIENT_SECRET
ENV OAUTH2_GOOGLE_CLIENT_SECRET=${OAUTH2_GOOGLE_CLIENT_SECRET}

ARG GOOGLE_REDIRECT_URI
ENV GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}

ARG ACCOUNT_CLOUDFLARE_API_TOKEN
ENV ACCOUNT_CLOUDFLARE_API_TOKEN=${ACCOUNT_CLOUDFLARE_API_TOKEN}

ARG ACCOUNT_CLOUDFLARE_API_ACCOUNT_ID
ENV ACCOUNT_CLOUDFLARE_API_ACCOUNT_ID=${ACCOUNT_CLOUDFLARE_API_ACCOUNT_ID}

ARG ACCOUNT_AZURE_KEY
ENV ACCOUNT_AZURE_KEY=${ACCOUNT_AZURE_KEY}

ARG CLOUD_CLOUDINARY_NAME
ENV CLOUD_CLOUDINARY_NAME=${CLOUD_CLOUDINARY_NAME}

ARG CLOUD_CLOUDINARY_API_KEY
ENV CLOUD_CLOUDINARY_API_KEY=${CLOUD_CLOUDINARY_API_KEY}

ARG CLOUD_CLOUDINARY_API_SECRET
ENV CLOUD_CLOUDINARY_API_SECRET=${CLOUD_CLOUDINARY_API_SECRET}

ARG OAUTH2_TIKTOK_CLIENT_ID
ENV OAUTH2_TIKTOK_CLIENT_ID=${OAUTH2_TIKTOK_CLIENT_ID}

ARG OAUTH2_TIKTOK_CLIENT_SECRET
ENV OAUTH2_TIKTOK_CLIENT_SECRET=${OAUTH2_TIKTOK_CLIENT_SECRET}

ARG REDIS_HOST
ENV REDIS_HOST=${REDIS_HOST}

ARG REDIS_PORT
ENV REDIS_PORT=${REDIS_PORT}

ARG REDIS_USERNAME
ENV REDIS_USERNAME=${REDIS_USERNAME}

ARG REDIS_PASSWORD
ENV REDIS_PASSWORD=${REDIS_PASSWORD}

COPY target/aishortvideo-0.0.1-SNAPSHOT.jar app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]

EXPOSE 9090