spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  #    show-sql: true

  security:
    jwtSecret: ${JWT_SECRET}
    jwtExpiration: 43200000 # 12h
    user:
      password: ankiney
      name: ankiney
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH2_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET}
            redirect-uri: "http://localhost:3000/api/auth/google-callback"
            scope:
              - email
              - profile

  data:
    redis:
      host: 88.222.212.40
      port: 6378

data:
  api:
    wikipedia:
      url: "https://%s.wikipedia.org/w/api.php?action=query&prop=extracts&exintro&explaintext&titles=%s&format=json"
    wikidata:
      url: "https://www.wikidata.org/w/api.php?action=wbsearchentities&search=%s&language=%s&uselang=%s&format=json"

account:
  cloudflare:
    apiToken: ${ACCOUNT_CLOUDFLARE_API_TOKEN}
    accountId: ${ACCOUNT_CLOUDFLARE_API_ACCOUNT_ID}
  azure:
    key: ${ACCOUNT_AZURE_KEY}

ai:
  chat:
    api: "https://api.cloudflare.com/client/v4/accounts/{account_id}/ai/run"
  image:
    api: "https://api.cloudflare.com/client/v4/accounts/{accountId}/ai/run"
  audio:
    api: "https://eastus.tts.speech.microsoft.com/cognitiveservices/v1"

model:
  chat: "/@cf/meta/llama-2-7b-chat-int8"
  image: "/@cf/stabilityai/stable-diffusion-xl-base-1.0"

cloud:
  cloudinary:
    name: ${CLOUD_CLOUDINARY_NAME}
    apiKey: ${CLOUD_CLOUDINARY_API_KEY}
    apiSecret: ${CLOUD_CLOUDINARY_API_SECRET}


