spring:
  application:
    name: aishortvideo

  datasource:
    password: ankiney
    url: jdbc:postgresql://88.222.212.40:5432/aishortvideo
    username: ankiney

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
