spring:
  application:
    name: aishortvideo

  datasource:
    password: ankiney
    url: jdbc:postgresql://88.222.212.40:5432/aishortvideo
    username: ankiney

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

data:
  api:
    wikipedia:
      url: "https://%s.wikipedia.org/w/api.php?action=query&prop=extracts&exintro&explaintext&titles=%s&format=json"
    wikidata:
      url: "https://www.wikidata.org/w/api.php?action=wbsearchentities&search=%s&language=%s&format=json"

account:
  cloudflare:
    apiToken: "C09eZOUy0yMiqrntcSXhOVuycS1OeIamcm1q1vXW"
    accountId: "8b1d2924f3ee32dfd5e67ef129176db4"

ai:
  chat:
    api: "https://api.cloudflare.com/client/v4/accounts/{account_id}/ai/run"

model:
  chat: "/@cf/meta/llama-2-7b-chat-int8"


