server:
  port: 9090

open:
  api:
    title: AI Short Video Editor
    version: v1.0.0
    description: AI Short Video Editor API
    serverUrl: http://localhost:9090
    serverName: Server Test

springdoc:
  swagger-ui:
    path: /api-docs

spring:
  application:
    name: AI-short-video

  datasource:
    password: ankiney
    url: jdbc:postgresql://88.222.212.40:5432/aishortvideo
    username: ankiney

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    jwtSecret: 251d12e6b0984b75a8c37277df474503aKn080104AiShortVideo
    jwtExpiration: 43200000 # 12h
    user:
      password: ankiney
      name: ankiney
  data:
    redis:
      host: 88.222.212.40
      port: 6378

data:
  api:
    wikipedia:
      url: "https://%s.wikipedia.org/w/api.php?action=query&prop=extracts&exintro&explaintext&titles=%s&format=json"
    wikidata:
      url: "https://www.wikidata.org/w/api.php?action=wbsearchentities&search=%s&language=%s&uselang=%s&format=json"

account:
  cloudflare:
    apiToken: "C09eZOUy0yMiqrntcSXhOVuycS1OeIamcm1q1vXW"
    accountId: "8b1d2924f3ee32dfd5e67ef129176db4"
  azure:
    key: "FuJNA6HCoFa7wkY3EbMtH1qlJyIZ1vJ96FcJmlLFyBtSF1Z6yRl5JQQJ99BFACYeBjFXJ3w3AAAYACOG8ws7"

ai:
  chat:
    api: "https://api.cloudflare.com/client/v4/accounts/{account_id}/ai/run"
  image:
    api: "https://api.cloudflare.com/client/v4/accounts/{accountId}/ai/run"
  audio:
    api: "https://eastus.tts.speech.microsoft.com/cognitiveservices/v1"

model:
  chat: "/@cf/meta/llama-2-7b-chat-int8"
  image: "/@cf/stabilityai/stable-diffusion-xl-base-1.0"

cloud:
  cloudinary:
    name: "dykyxn2rc"
    apiKey: "687762494213714"
    apiSecret: "7XNB1N8X33I7qsGmCwWV9fUUQy8"


