name: Project AI Short Video Editor

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      POSTGRES_USERNAME: ${{ secrets.POSTGRES_USERNAME }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      OAUTH2_GOOGLE_CLIENT_ID: ${{ secrets.OAUTH2_GOOGLE_CLIENT_ID }}
      OAUTH2_GOOGLE_CLIENT_SECRET: ${{ secrets.OAUTH2_GOOGLE_CLIENT_SECRET }}
      ACCOUNT_CLOUDFLARE_API_TOKEN: ${{ secrets.ACCOUNT_CLOUDFLARE_API_TOKEN }}
      ACCOUNT_CLOUDFLARE_API_ACCOUNT_ID: ${{ secrets.ACCOUNT_CLOUDFLARE_API_ACCOUNT_ID }}
      ACCOUNT_AZURE_KEY: ${{ secrets.ACCOUNT_AZURE_KEY }}
      CLOUD_CLOUDINARY_NAME: ${{ secrets.CLOUD_CLOUDINARY_NAME }}
      CLOUD_CLOUDINARY_API_KEY: ${{ secrets.CLOUD_CLOUDINARY_API_KEY }}
      CLOUD_CLOUDINARY_API_SECRET: ${{ secrets.CLOUD_CLOUDINARY_API_SECRET }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run Unit Tests
        run: mvn test

      - name: Build with Maven
        run: mvn clean install

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: devopshcmus/website-backend-ai-short-video-editor:latest
          build-args: |
            POSTGRES_USERNAME=${{ secrets.POSTGRES_USERNAME }}
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            POSTGRES_URL=${{ secrets.POSTGRES_URL }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            OAUTH2_GOOGLE_CLIENT_ID=${{ secrets.OAUTH2_GOOGLE_CLIENT_ID }}
            OAUTH2_GOOGLE_CLIENT_SECRET=${{ secrets.OAUTH2_GOOGLE_CLIENT_SECRET }}
            ACCOUNT_CLOUDFLARE_API_TOKEN=${{ secrets.ACCOUNT_CLOUDFLARE_API_TOKEN }}
            ACCOUNT_CLOUDFLARE_API_ACCOUNT_ID=${{ secrets.ACCOUNT_CLOUDFLARE_API_ACCOUNT_ID }}
            ACCOUNT_AZURE_KEY=${{ secrets.ACCOUNT_AZURE_KEY }}
            CLOUD_CLOUDINARY_NAME=${{ secrets.CLOUD_CLOUDINARY_NAME }}
            CLOUD_CLOUDINARY_API_KEY=${{ secrets.CLOUD_CLOUDINARY_API_KEY }}
            CLOUD_CLOUDINARY_API_SECRET=${{ secrets.CLOUD_CLOUDINARY_API_SECRET }}
