name: Project AI Short Video Editor

# Chạy khi có push hoặc pull request vào nhánh main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    # Chạy trên môi trường ubuntu mới nhất
    runs-on: ubuntu-latest

    # Biến môi trường được lấy từ Github secrets
    env:
      POSTGRES_USERNAME: ${{ secrets.POSTGRES_USERNAME }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      OAUTH2_GOOGLE_CLIENT_ID: ${{ secrets.OAUTH2_GOOGLE_CLIENT_ID }}
      OAUTH2_GOOGLE_CLIENT_SECRET: ${{ secrets.OAUTH2_GOOGLE_CLIENT_SECRET }}
      GOOGLE_REDIRECT_URI: ${{ secrets.GOOGLE_REDIRECT_URI }}
      ACCOUNT_CLOUDFLARE_API_TOKEN: ${{ secrets.ACCOUNT_CLOUDFLARE_API_TOKEN }}
      ACCOUNT_CLOUDFLARE_API_ACCOUNT_ID: ${{ secrets.ACCOUNT_CLOUDFLARE_API_ACCOUNT_ID }}
      ACCOUNT_AZURE_KEY: ${{ secrets.ACCOUNT_AZURE_KEY }}
      CLOUD_CLOUDINARY_NAME: ${{ secrets.CLOUD_CLOUDINARY_NAME }}
      CLOUD_CLOUDINARY_API_KEY: ${{ secrets.CLOUD_CLOUDINARY_API_KEY }}
      CLOUD_CLOUDINARY_API_SECRET: ${{ secrets.CLOUD_CLOUDINARY_API_SECRET }}
      OAUTH2_TIKTOK_CLIENT_ID: ${{ secrets.OAUTH2_TIKTOK_CLIENT_ID }}
      OAUTH2_TIKTOK_CLIENT_SECRET: ${{ secrets.OAUTH2_TIKTOK_CLIENT_SECRET }}

    # Bắt đầu các bước
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run Unit Tests
        run: mvn test

      # Build project ra file .jar trong thư mục target/.
      - name: Build with Maven
        run: mvn clean install

      # Đăng nhập vào Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Cài và khởi tạo Docker Buildx, một công cụ mạnh cho việc build image
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Thư mục gốc chứa Dockerfile để build image
          file: Dockerfile
          push: true # Bắt buộc để đẩy image lên hub
          tags: devopshcmus/website-backend-ai-short-video-editor:latest
          # Truyền vào Dockerfile
          build-args: |
            POSTGRES_USERNAME=${{ secrets.POSTGRES_USERNAME }}
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            POSTGRES_URL=${{ secrets.POSTGRES_URL }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            OAUTH2_GOOGLE_CLIENT_ID=${{ secrets.OAUTH2_GOOGLE_CLIENT_ID }}
            OAUTH2_GOOGLE_CLIENT_SECRET=${{ secrets.OAUTH2_GOOGLE_CLIENT_SECRET }}
            GOOGLE_REDIRECT_URI=${{ secrets.GOOGLE_REDIRECT_URI }}
            ACCOUNT_CLOUDFLARE_API_TOKEN=${{ secrets.ACCOUNT_CLOUDFLARE_API_TOKEN }}
            ACCOUNT_CLOUDFLARE_API_ACCOUNT_ID=${{ secrets.ACCOUNT_CLOUDFLARE_API_ACCOUNT_ID }}
            ACCOUNT_AZURE_KEY=${{ secrets.ACCOUNT_AZURE_KEY }}
            CLOUD_CLOUDINARY_NAME=${{ secrets.CLOUD_CLOUDINARY_NAME }}
            CLOUD_CLOUDINARY_API_KEY=${{ secrets.CLOUD_CLOUDINARY_API_KEY }}
            CLOUD_CLOUDINARY_API_SECRET=${{ secrets.CLOUD_CLOUDINARY_API_SECRET }}
            OAUTH2_TIKTOK_CLIENT_ID: ${{ secrets.OAUTH2_TIKTOK_CLIENT_ID }}
            OAUTH2_TIKTOK_CLIENT_SECRET: ${{ secrets.OAUTH2_TIKTOK_CLIENT_SECRET }}
      - name: Trigger Render deploy
        run: curl -X POST https://api.render.com/deploy/srv-d1n8ih6mcj7s73bqnkhg?key=JPsbXwKVbfM